package com.employee.management.service;

import java.util.Optional;
import java.util.List;
import java.math.BigDecimal;

import org.springframework.stereotype.Service;

import com.employee.management.dto.OrderResponse;
import com.employee.management.model.Order;
import com.employee.management.model.OrderStatus;
import com.employee.management.repository.StudentRepository;
import com.employee.management.repository.OrderRepository;
import com.employee.management.model.CartItem;
import com.employee.management.model.OrderItem;
import com.employee.management.model.Student;
import com.employee.management.service.CartService;

import lombok.RequiredArgsConstructor;



@Service
@RequiredArgsConstructor
public class OrderServices {

    private final CartService cartService;
    private final StudentRepository studentRepository;
    private final OrderRepository orderRepository;

    public Optional<OrderResponse> createOrder(Integer studentId) {
        // Validate the cart
        List<CartItem> cartItems = cartService.getCartItems(studentId);
        if(cartItems.isEmpty()) {
            return Optional.empty(); // No items in the cart, cannot create an order
        }
        //Validate the user
        Optional<Student> studentOpt = studentRepository.findById(studentId);
        if (studentOpt.isEmpty()) {
            return Optional.empty(); // Student not found, cannot create an order
        }
        Student student = studentOpt.get();
        // Calculate total amount
        BigDecimal totalPrice = cartItems.stream()
                .map(CartItem::getPrice) // why map is used: map is used to transform each CartItem into its price (BigDecimal). It takes each CartItem from the stream and applies the getPrice() method to extract the price.
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        // Create order 
        Order order = new Order();
        order.setStudent(student);
        order.setStatus(OrderStatus.CONFIRMED);
        order.setTotalPrice(totalPrice);
        // List<OrderItem> orderItems = cartItems.stream()
        //         .map(CartItem item ->  new OrderItem(
        //             null, // id will be generated by the database
        //             item.getProduct(),
        //             item.getQuantity(),
        //             item.getPrice(),
        //             order
        //         )).toList();
        List<OrderItem> orderItems = cartItems.stream()
                .map(item -> {
                    OrderItem orderItem = new OrderItem();
                    orderItem.setProduct(item.getProduct());
                    orderItem.setQuantity(item.getQuantity());
                    orderItem.setPrice(item.getPrice());
                    orderItem.setOrder(order); // set the order reference in each OrderItem
                    return orderItem;
                })
                .toList();
        order.setItems(orderItems);
        Order savedOrder = orderRepository.save(order);
        // Clear the cart
        cartService.clearCart(studentId);
        
    }
}
